## 강의실 데이터 추가하기.
- 동아리방
- 학부방
- 식당

등

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np

In [3]:
basic_data_path = '/content/drive/MyDrive/mapinskhu(26~)/Data/26-2/basic_room_data.csv'
add_data_path = '/content/drive/MyDrive/mapinskhu(26~)/Data/26-2/add_room_data.csv'

In [4]:
bdf = pd.read_csv(basic_data_path)
adf = pd.read_csv(add_data_path) # 데이터 공개 x

In [5]:
bdf

       kwan_name   room  floor  room_image  room_type
0           새천년관   7207      2         NaN        NaN
1           새천년관   7208      2         NaN        NaN
2            월당관   3402      4         NaN        NaN
3           새천년관   7308      3         NaN        NaN
4           새천년관   7309      3         NaN        NaN
5            승연관   1504      5         NaN        NaN
6            승연관   1503      5         NaN        NaN
7            승연관   1505      5         NaN        NaN
8            월당관   3502      5         NaN        NaN
9           미가엘관   M401      4         NaN        NaN
10         정보과학관   6206      2         NaN        NaN
11           월당관   3302      3         NaN        NaN
12         정보과학관   6201      2         NaN        NaN
13          미가엘관   M205      2         NaN        NaN
14         정보과학관   6110      1         NaN        NaN
15          미가엘관   M301      3         NaN        NaN
16          새천년관   7304      3         NaN        NaN
17          새천년관   7307      3         NaN        NaN
18          새천년관   7202      2         NaN        NaN
19          새천년관   7303      3         NaN        NaN
20          새천년관   7206      2         NaN        NaN
21          새천년관   7305      3         NaN        NaN
22          새천년관   7301      3         NaN        NaN
23          새천년관   7417      4         NaN        NaN
24          새천년관   7306      3         NaN        NaN
25          새천년관   7616      6         NaN        NaN
26           승연관   1501      5         NaN        NaN
27           승연관   1502      5         NaN        NaN
28         정보과학관   6404      4         NaN        NaN
29          미가엘관   M404      4         NaN        NaN
30          미가엘관   M406      4         NaN        NaN
31           승연관   1508      5         NaN        NaN
32           승연관   1507      5         NaN        NaN
33          미가엘관   M407      4         NaN        NaN
34          새천년관   7204      2         NaN        NaN
35           월당관   3301      3         NaN        NaN
36           월당관   3401      4         NaN        NaN
37           일만관   B105      1         NaN        NaN
38           월당관   3501      5         NaN        NaN
39          미가엘관   M402      4         NaN        NaN
40           승연관   1506      5         NaN        NaN
41          새천년관   7107      1         NaN        NaN
42          새천년관   7205      2         NaN        NaN
43  성미가엘성당&피츠버그홀   9301      3         NaN        NaN
44          미가엘관   M403      4         NaN        NaN
45           나눔관  5C301      3         NaN        NaN
46  성미가엘성당&피츠버그홀   9990      9         NaN        NaN
47          새천년관   7201      2         NaN        NaN
48         정보과학관   6406      4         NaN        NaN
49         정보과학관   6202      2         NaN        NaN
50         정보과학관   6405      4         NaN        NaN
51         정보과학관   6403      4         NaN        NaN
52         정보과학관   6402      4         NaN        NaN
53  성미가엘성당&피츠버그홀   9101      1         NaN        NaN
54          새천년관   7302      3         NaN        NaN
55         정보과학관   6109      1         NaN        NaN

In [6]:
bdf['kwan_name'].unique()

array(['새천년관', '월당관', '승연관', '미가엘관', '정보과학관', '일만관', '성미가엘성당&피츠버그홀',
       '나눔관'], dtype=object)

In [7]:
adf

       용도구분     용도분류    건물명     층        호  실    세부용도
0    교육기본시설    실험실습실   구두인관   NaN      1A103    실험실습실
1    교육기본시설     대학본부   구두인관   NaN      1A101      사무실
2    교육기본시설     대학본부   구두인관   NaN      1A102      사무실
3    교육기본시설     대학본부   구두인관   NaN      1A104      사무실
4    교육기본시설     대학본부   구두인관   NaN      1A201      사무실
..      ...      ...    ...   ...         ...      ...
393    지원시설   학생기숙사   행복기숙사    6층     549.69      기숙사
394    지원시설   학생기숙사   행복기숙사    7층     549.69      기숙사
395    지원시설   학생기숙사   행복기숙사    8층     549.69      기숙사
396    지원시설   학생기숙사   행복기숙사    9층     549.69      기숙사
397    지원시설   학생기숙사   행복기숙사  지하1층   1,010.19      기숙사

[398 rows x 6 columns]

In [8]:
adf.columns = ['a', 'b', 'kwan_name', 'c', 'room', 'detail']
adf

          a        b kwan_name     c        room   detail
0    교육기본시설    실험실습실      구두인관   NaN      1A103    실험실습실
1    교육기본시설     대학본부      구두인관   NaN      1A101      사무실
2    교육기본시설     대학본부      구두인관   NaN      1A102      사무실
3    교육기본시설     대학본부      구두인관   NaN      1A104      사무실
4    교육기본시설     대학본부      구두인관   NaN      1A201      사무실
..      ...      ...       ...   ...         ...      ...
393    지원시설   학생기숙사      행복기숙사    6층     549.69      기숙사
394    지원시설   학생기숙사      행복기숙사    7층     549.69      기숙사
395    지원시설   학생기숙사      행복기숙사    8층     549.69      기숙사
396    지원시설   학생기숙사      행복기숙사    9층     549.69      기숙사
397    지원시설   학생기숙사      행복기숙사  지하1층   1,010.19      기숙사

[398 rows x 6 columns]

# 할 것

1. 관, 호실, 세부 만 남길 것이다. (kwan, room, detail)

2. adf에서 사용하는 관 이름이 맵인스쿠에서 사용하는 이름과 다르기에 맵인스쿠 이름과 동일하게 바꿔줄 것이다.

3. 세부는 해당 강의실에 대한 정보가 담겨 있기에 층(세부) 형식으로 사용하고 버릴 것이다.

4. 행복기숙사, 주방 행은 버릴 것이다. (인덱스 387 ~ 397, 10)

5. floor, room_image, room_type 컬럼 만들기

6. 맵인스쿠에서 강의가 없는 강의실은 검색을 해야만 확인이 가능하다.  강의가 없는 강의실도 검색하지 않아도 보일 수 있게 바꿀지 생각해보아야 한다.

## 관, 호실, 세부만 남기기

In [9]:
adf2 = adf[['kwan_name', 'room', 'detail']]

adf2.kwan_name = adf2.kwan_name.str.replace(' ', '')
adf2.room = adf2.room.str.replace(' ', '')
adf2.detail = adf2.detail.str.replace(' ', '')
adf2

/tmp/ipykernel_817/462663958.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adf2.kwan_name = adf2.kwan_name.str.replace(' ', '')
/tmp/ipykernel_817/462663958.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adf2.room = adf2.room.str.replace(' ', '')
/tmp/ipykernel_817/462663958.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adf2.detail = adf2.detail.str.replace(' ', '')

    kwan_name      room detail
0        구두인관     1A103  실험실습실
1        구두인관     1A101    사무실
2        구두인관     1A102    사무실
3        구두인관     1A104    사무실
4        구두인관     1A201    사무실
..        ...       ...    ...
393     행복기숙사    549.69    기숙사
394     행복기숙사    549.69    기숙사
395     행복기숙사    549.69    기숙사
396     행복기숙사    549.69    기숙사
397     행복기숙사  1,010.19    기숙사

[398 rows x 3 columns]

In [10]:
adf2.head(10)

  kwan_name   room detail
0      구두인관  1A103  실험실습실
1      구두인관  1A101    사무실
2      구두인관  1A102    사무실
3      구두인관  1A104    사무실
4      구두인관  1A201    사무실
5      구두인관  1A202    사무실
6      구두인관  1A203    사무실
7      구두인관  1A204    사무실
8      구두인관  1A205    사무실
9     인문사회관  B7101     식당

## 행복기숙사 & 주방 삭제

In [11]:
adf2.drop(index=range(387, 398), inplace=True)
adf2.drop(index=[10], inplace=True)

/tmp/ipykernel_817/355697600.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adf2.drop(index=range(387, 398), inplace=True)
/tmp/ipykernel_817/355697600.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adf2.drop(index=[10], inplace=True)

In [12]:
adf2.head(15)

   kwan_name   room  detail
0       구두인관  1A103   실험실습실
1       구두인관  1A101     사무실
2       구두인관  1A102     사무실
3       구두인관  1A104     사무실
4       구두인관  1A201     사무실
5       구두인관  1A202     사무실
6       구두인관  1A203     사무실
7       구두인관  1A204     사무실
8       구두인관  1A205     사무실
9      인문사회관  B7101      식당
11     인문사회관  B7102    인권센터
12     인문사회관   7706  세미나실습실
13     인문사회관   7701   교수연구실
14     인문사회관   7702   교수연구실
15     인문사회관   7703   교수연구실

## 관 이름 일치시키기

In [13]:
adf2['kwan_name'].unique()

array(['구두인관', '인문사회관', '나눔관', '중앙도서관', '대학성당', '일만관', '월당관', '성미가엘관',
       '이천환기념관', '승연관'], dtype=object)

In [14]:
adf3 = adf2.copy()

In [15]:
conditionlist = [
    (adf3['kwan_name'] == '구두인관'), #new
    (adf3['kwan_name'] == '인문사회관'),
    (adf3['kwan_name'] == '나눔관'),
    (adf3['kwan_name'] == '중앙도서관'), #new
    (adf3['kwan_name'] == '대학성당'),
    (adf3['kwan_name'] == '일만관'),
    (adf3['kwan_name'] == '월당관'),
    (adf3['kwan_name'] == '성미가엘관'),
    (adf3['kwan_name'] == '이천환기념관'),
    (adf3['kwan_name'] == '승연관')
]

choicelist = [
    '구두인관',
    '새천년관',
    '나눔관',
    '중앙도서관',
    '성미가엘성당&피츠버그홀',
    '일만관',
    '월당관',
    '미가엘관',
    '정보과학관',
    '승연관'
]

adf3['kwan_name'] = np.select(conditionlist, choicelist, default='미정')

In [16]:
adf3.head(15)

   kwan_name   room  detail
0       구두인관  1A103   실험실습실
1       구두인관  1A101     사무실
2       구두인관  1A102     사무실
3       구두인관  1A104     사무실
4       구두인관  1A201     사무실
5       구두인관  1A202     사무실
6       구두인관  1A203     사무실
7       구두인관  1A204     사무실
8       구두인관  1A205     사무실
9       새천년관  B7101      식당
11      새천년관  B7102    인권센터
12      새천년관   7706  세미나실습실
13      새천년관   7701   교수연구실
14      새천년관   7702   교수연구실
15      새천년관   7703   교수연구실

## floor, room_image, room_type 컬럼 추가

In [17]:
adf4 = adf3.copy()

In [18]:
adf4 = adf4.assign(floor=np.nan,
                   room_image=np.nan,
                   room_type=np.nan)
adf4

    kwan_name   room detail  floor  room_image  room_type
0        구두인관  1A103  실험실습실    NaN         NaN        NaN
1        구두인관  1A101    사무실    NaN         NaN        NaN
2        구두인관  1A102    사무실    NaN         NaN        NaN
3        구두인관  1A104    사무실    NaN         NaN        NaN
4        구두인관  1A201    사무실    NaN         NaN        NaN
..        ...    ...    ...    ...         ...        ...
382       승연관   1504    강의실    NaN         NaN        NaN
383       승연관   1505    강의실    NaN         NaN        NaN
384       승연관   1506    강의실    NaN         NaN        NaN
385       승연관   1507    강의실    NaN         NaN        NaN
386       승연관   1508    강의실    NaN         NaN        NaN

[386 rows x 6 columns]

## floor 추가

안내실과 7417-B가 포함된 행은 예외로 나중에 직접 수정해준다.

In [19]:

def extract_floor(val):
    # 결측치이거나 문자열 변환 후 길이가 부족한 경우 처리
    if pd.isna(val):
        return None

    text = str(val)
    # 길이가 5 이상이면 -> 3번째 글자 (인덱스 2)
    if len(text) >= 5:
        return text[2]
    # 길이가 5 미만 -> 2번째 글자 (인덱스 1)
    elif len(text) >= 2:
        return text[1]
    else:
        return None

# floor 추가
adf4['floor'] = adf4['room'].apply(extract_floor)

In [20]:
adf4

    kwan_name   room detail floor  room_image  room_type
0        구두인관  1A103  실험실습실     1         NaN        NaN
1        구두인관  1A101    사무실     1         NaN        NaN
2        구두인관  1A102    사무실     1         NaN        NaN
3        구두인관  1A104    사무실     1         NaN        NaN
4        구두인관  1A201    사무실     2         NaN        NaN
..        ...    ...    ...   ...         ...        ...
382       승연관   1504    강의실     5         NaN        NaN
383       승연관   1505    강의실     5         NaN        NaN
384       승연관   1506    강의실     5         NaN        NaN
385       승연관   1507    강의실     5         NaN        NaN
386       승연관   1508    강의실     5         NaN        NaN

[386 rows x 6 columns]

## bdf 에 존재하는 room 제거하기 (중복 강의실 제거)

bdf 55행, adf4 386행 -> 중복 제거 후 adf4_cleaned 332행

In [21]:
# 기준이 되는 공통 컬럼명 : room
# 1. bdf테이블의 room에 존재하지 않는(~) adf의 room값 행만 남기기
adf4_cleaned = adf4[~adf4['room'].isin(bdf['room'])].copy()

# 2. 인덱스 0부터 깔끔하게 재정렬
adf4_cleaned = adf4_cleaned.reset_index(drop=True)

## detail 사용 후 버리기

In [22]:
adf4_cleaned.room = adf4_cleaned.room + '(' + adf4_cleaned.detail + ')'
adf4_cleaned = adf4_cleaned.drop('detail', axis=1)

In [25]:
adf4_cleaned

    kwan_name             room floor  room_image  room_type
0        구두인관     1A103(실험실습실)     1         NaN        NaN
1        구두인관       1A101(사무실)     1         NaN        NaN
2        구두인관       1A102(사무실)     1         NaN        NaN
3        구두인관       1A104(사무실)     1         NaN        NaN
4        구두인관       1A201(사무실)     2         NaN        NaN
..        ...              ...   ...         ...        ...
327       승연관      1305(대학발전실)     3         NaN        NaN
328       승연관     1306(대외부총장실)     3         NaN        NaN
329       승연관  1405(외래교수공동연구실)     4         NaN        NaN
330       승연관       1406(세미나실)     4         NaN        NaN
331       승연관       1407(세미나실)     4         NaN        NaN

[332 rows x 5 columns]

In [26]:
adf4_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   kwan_name   332 non-null    object
 1   room        329 non-null    object
 2   floor       332 non-null    object
 3   room_image  0 non-null      float64
 4   room_type   0 non-null      float64
dtypes: float64(2), object(3)
memory usage: 13.1+ KB

## 안내실(경비실), 7417-B 처리하기

인덱스 74, 83

In [35]:
adf4_cleaned[adf4_cleaned['room'].str.contains('7417-B|경비', na=False)]

   kwan_name         room floor  room_image  room_type
74      새천년관  7417-B(휴게실)     4         NaN        NaN
83      새천년관     안내실(경비실)     1         NaN        NaN

In [36]:
# 1. 특정 텍스트가 포함된 조건을 마스크(mask)로 정의
mask = adf4_cleaned['room'].str.contains('7417-B', na=False)
# 2. loc[행_조건, '수정할컬럼명'] = 변경할_값
adf4_cleaned.loc[mask, 'floor'] = '4'

mask = adf4_cleaned['room'].str.contains('경비', na=False)
adf4_cleaned.loc[mask, 'floor'] = '1'

In [37]:
adf4_cleaned.loc[74]

kwan_name            새천년관
room          7417-B(휴게실)
floor                   4
room_image            NaN
room_type             NaN
Name: 74, dtype: object

In [38]:
adf4_cleaned.loc[83]

kwan_name         새천년관
room          안내실(경비실)
floor                1
room_image         NaN
room_type          NaN
Name: 83, dtype: object

In [39]:
final_adf = adf4_cleaned.copy()

## bdf + adf

In [40]:
# 두 데이터프레임(df1, df2)을 행 방향(axis=0)으로 합치기
final_df = pd.concat([bdf, final_adf], ignore_index=True)

In [41]:
final_df

    kwan_name             room floor  room_image  room_type
0        새천년관             7207     2         NaN        NaN
1        새천년관             7208     2         NaN        NaN
2         월당관             3402     4         NaN        NaN
3        새천년관             7308     3         NaN        NaN
4        새천년관             7309     3         NaN        NaN
..        ...              ...   ...         ...        ...
383       승연관      1305(대학발전실)     3         NaN        NaN
384       승연관     1306(대외부총장실)     3         NaN        NaN
385       승연관  1405(외래교수공동연구실)     4         NaN        NaN
386       승연관       1406(세미나실)     4         NaN        NaN
387       승연관       1407(세미나실)     4         NaN        NaN

[388 rows x 5 columns]

In [42]:
final_df.to_csv('all_rooms.csv', index=False, encoding='utf-8-sig')

## 위에서 만든 테이블로 모든 강의동 csv 도 만들자.
하지만 이미 기존 all_kwan에 존재하여 넘어감.

In [45]:
kwan_df = final_df[['kwan_name']]
kwan_df

    kwan_name
0        새천년관
1        새천년관
2         월당관
3        새천년관
4        새천년관
..        ...
383       승연관
384       승연관
385       승연관
386       승연관
387       승연관

[388 rows x 1 columns]

In [46]:
# 'kwan_name' 컬럼 기준 중복 제거
kwan_df2 = kwan_df.drop_duplicates(subset=['kwan_name']).reset_index(drop=True)
kwan_df2

      kwan_name
0          새천년관
1           월당관
2           승연관
3          미가엘관
4         정보과학관
5           일만관
6  성미가엘성당&피츠버그홀
7           나눔관
8          구두인관
9         중앙도서관